
package artifact;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.2
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "CalculatorWSService", targetNamespace = "http://book/", wsdlLocation = "http://localhost:8080/soapws/CalculatorWS?wsdl")
public class CalculatorWSService
    extends Service
{

    private static final URL CALCULATORWSSERVICE_WSDL_LOCATION;
    private static final WebServiceException CALCULATORWSSERVICE_EXCEPTION;
    private static final QName CALCULATORWSSERVICE_QNAME = new QName("http://book/", "CalculatorWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/soapws/CalculatorWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULATORWSSERVICE_WSDL_LOCATION = url;
        CALCULATORWSSERVICE_EXCEPTION = e;
    }

    public CalculatorWSService() {
        super(__getWsdlLocation(), CALCULATORWSSERVICE_QNAME);
    }

    public CalculatorWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULATORWSSERVICE_QNAME, features);
    }

    public CalculatorWSService(URL wsdlLocation) {
        super(wsdlLocation, CALCULATORWSSERVICE_QNAME);
    }

    public CalculatorWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULATORWSSERVICE_QNAME, features);
    }

    public CalculatorWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculatorWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculatorWS
     */
    @WebEndpoint(name = "CalculatorWSPort")
    public CalculatorWS getCalculatorWSPort() {
        return super.getPort(new QName("http://book/", "CalculatorWSPort"), CalculatorWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculatorWS
     */
    @WebEndpoint(name = "CalculatorWSPort")
    public CalculatorWS getCalculatorWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://book/", "CalculatorWSPort"), CalculatorWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULATORWSSERVICE_EXCEPTION!= null) {
            throw CALCULATORWSSERVICE_EXCEPTION;
        }
        return CALCULATORWSSERVICE_WSDL_LOCATION;
    }

}
