version: '3.4'

services:
  database:
    image: postgres:9
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: My01pass # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: school # The PostgreSQL default database (automatically created at first launch)
  wildfly:
    build:
      context: .
      dockerfile: Dockerfile
    links: 
      - database
    ports:
      - 8080:8080
      - 9990:9990
  command-line:
    image: maven:3-openjdk-17
    command: tail -f /dev/null
    links: 
      - database
      - wildfly
    volumes:
      - ..:/workspace
  